nginx:
    build: ./nginx
    links:
        - node
    volumes_from:
        - node
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./ssl-certs/etc/letsencrypt:/etc/letsencrypt
        - ./ssl-certs/var/lib/letsencrypt:/var/lib/letsencrypt
node:
    build: ./node
    container_name: node
    restart: always
    ports:
        - 3000
    volumes:
        - ./node/app:/srv/www/app
    env_file:
        - ./node/app/.env

