node:
    build: ./
    ports:
        - 80:3000
    environment:
        db: '${KILOMETRIKISA_DB}'
        dbuser: '${KILOMETRIKISA_DBUSER}'
        dbpassword: '${KILOMETRIKISA_DBPASSWORD}'
        dbhost: '${KILOMETRIKISA_DBHOST}'
