nginx:
    build: ./nginx
    links:
        - node
    volumes_from:
        - node
    ports:
        - "80:80"
node:
    build: ./node
    restart: always
    ports:
        - 3000
    volumes:
        - ./node/app:/srv/www/app
    environment:
        db: 'stava2kilometrikisa'
        dbuser: 'stava2kilometrikisa'
        dbpassword: 'CHsEkhov5Iz6'
        dbhost: 'ds035975.mlab.com:35975'