nginx:
    build: ./nginx
    links:
        - node
    ports:
        - "80:80"
node:
    build: ./node
    ports:
        - 3000
    environment:
        db: 'stava2kilometrikisa'
        dbuser: 'stava2kilometrikisa'
        dbpassword: 'CHsEkhov5Iz6'
        dbhost: 'ds035975.mlab.com:35975'