nginx:
    build: ./nginx
    links:
        - node
    volumes_from:
        - node
    ports:
        - "80:80"
node:
    build: ./node
    container_name: node
    restart: always
    ports:
        - 3000
    volumes:
        - ./node/app:/srv/www/app
    environment:
        db: '${KILOMETRIKISA_DB}'
        dbuser: '${KILOMETRIKISA_DBUSER}'
        dbpassword: '${KILOMETRIKISA_DBPASSWORD}'
        dbhost: '${KILOMETRIKISA_DBHOST}'
        STRAVA_ACCESS_TOKEN: '${STRAVA_ACCESS_TOKEN}'
        STRAVA_CLIENT_ID: '${STRAVA_CLIENT_ID}'
        STRAVA_CLIENT_SECRET: '${STRAVA_CLIENT_SECRET}'
        STRAVA_REDIRECT_URI: '${STRAVA_REDIRECT_URI}'